In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
## load DataSet
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## Preprocess the data
## Drop irrelevant features

data=data.drop(['RowNumber','CustomerId','Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
## Encode categorical variable

label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [9]:
## oneHot encode Geography

from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
## Combine one hot encoded columns with original data

data=pd.concat([data.drop('Geography', axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [20]:
## Save the encoders and scalar

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [21]:
## Divide the dataset into dependent and independent feature

X=data.drop('Exited', axis=1)
y=data['Exited']

## Split the data in training and testing sets

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [26]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [27]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [28]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

In [29]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

## ANN Implementation

In [31]:
pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.19.0-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.2.2-py3-none-any.whl.metadata (2.6 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Downloading flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google-pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (4.25.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (1.16.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (4.11.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (1.14.1)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.71.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
Collecting tensorboard~=2.19.0 (from tensorflow)
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.5.0 (from tensorflow)
  Downloading keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\gprai\anaconda3\lib\site-packages (from tensorflow) (3.11.0)
Collecting ml-dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.1-cp312-cp312-win_amd64.whl.metadata (22 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\gprai\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in c:\users\gprai\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow) (13.7.1)
Collecting namex (from keras>=3.5.0->tensorflow)
  Downloading namex-0.0.9-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.5.0->tensorflow)
  Downloading optree-0.15.0-cp312-cp312-win_amd64.whl.metadata (49 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\gprai\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gprai\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\gprai\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gprai\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.1.31)
Requirement already satisfied: markdown>=2.6.8 in c:\users\gprai\anaconda3\lib\site-packages (from tensorboard~=2.19.0->tensorflow) (3.4.1)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.19.0->tensorflow)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\gprai\anaconda3\lib\site-packages (from tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\gprai\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\gprai\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\gprai\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\gprai\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.0)
Downloading tensorflow-2.19.0-cp312-cp312-win_amd64.whl (376.0 MB)
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/376.0 MB 284.3 kB/s eta 0:22:01
   ---------------------------------------- 0.5/376.0 MB 284.3 kB/s eta 0:22:01
   ---------------------------------------- 0.5/376.0 MB 284.3 kB/s eta 0:22:01
   ---------------------------------------- 0.8/376.0 MB 345.8 kB/s eta 0:18:05
   ---------------------------------------- 0.8/376.0 MB 345.8 kB/s eta 0:18:05
   ---------------------------------------- 1.0/376.0 MB 396.2 kB/s eta 0:15:47
   ---------------------------------------- 1.0/376.0 MB 396.2 kB/s eta 0:15:47
   ---------------------------------------- 1.0/376.0 MB 396.2 kB/s eta 0:15:47
   ---------------------------------------- 1.3/376.0 MB 422.0 kB/s eta 0:14:48
   ---------------------------------------- 1.3/376.0 MB 422.0 kB/s eta 0:14:48
   ---------------------------------------- 1.6/376.0 MB 448.6 kB/s eta 0:13:55
   ---------------------------------------- 1.6/376.0 MB 448.6 kB/s eta 0:13:55
   ---------------------------------------- 1.6/376.0 MB 448.6 kB/s eta 0:13:55
   ---------------------------------------- 1.8/376.0 MB 421.1 kB/s eta 0:14:49
   ---------------------------------------- 1.8/376.0 MB 421.1 kB/s eta 0:14:49
   ---------------------------------------- 1.8/376.0 MB 421.1 kB/s eta 0:14:49
   ---------------------------------------- 2.1/376.0 MB 433.3 kB/s eta 0:14:23
   ---------------------------------------- 2.1/376.0 MB 433.3 kB/s eta 0:14:23
   ---------------------------------------- 2.4/376.0 MB 437.2 kB/s eta 0:14:15
   ---------------------------------------- 2.4/376.0 MB 437.2 kB/s eta 0:14:15
   ---------------------------------------- 2.4/376.0 MB 437.2 kB/s eta 0:14:15
   ---------------------------------------- 2.4/376.0 MB 437.2 kB/s eta 0:14:15
   ---------------------------------------- 2.6/376.0 MB 426.5 kB/s eta 0:14:36
   ---------------------------------------- 2.6/376.0 MB 426.5 kB/s eta 0:14:36
   ---------------------------------------- 2.6/376.0 MB 426.5 kB/s eta 0:14:36
   ---------------------------------------- 2.9/376.0 MB 422.6 kB/s eta 0:14:43
   ---------------------------------------- 2.9/376.0 MB 422.6 kB/s eta 0:14:43
   ---------------------------------------- 2.9/376.0 MB 422.6 kB/s eta 0:14:43
   ---------------------------------------- 3.1/376.0 MB 423.2 kB/s eta 0:14:41
   ---------------------------------------- 3.1/376.0 MB 423.2 kB/s eta 0:14:41
   ---------------------------------------- 3.4/376.0 MB 431.1 kB/s eta 0:14:25
   ---------------------------------------- 3.7/376.0 MB 449.7 kB/s eta 0:13:48
   ---------------------------------------- 3.7/376.0 MB 449.7 kB/s eta 0:13:48
   ---------------------------------------- 3.9/376.0 MB 470.7 kB/s eta 0:13:11
   ---------------------------------------- 4.2/376.0 MB 490.5 kB/s eta 0:12:38
   ---------------------------------------- 4.2/376.0 MB 490.5 kB/s eta 0:12:38
   ---------------------------------------- 4.5/376.0 MB 496.2 kB/s eta 0:12:29
   ---------------------------------------- 4.5/376.0 MB 496.2 kB/s eta 0:12:29
    --------------------------------------- 5.0/376.0 MB 521.6 kB/s eta 0:11:52
    --------------------------------------- 5.2/376.0 MB 542.1 kB/s eta 0:11:24
    --------------------------------------- 5.8/376.0 MB 583.3 kB/s eta 0:10:35
    --------------------------------------- 6.0/376.0 MB 600.1 kB/s eta 0:10:17
    --------------------------------------- 6.3/376.0 MB 609.6 kB/s eta 0:10:07
    --------------------------------------- 6.3/376.0 MB 609.6 kB/s eta 0:10:07
    --------------------------------------- 6.6/376.0 MB 617.5 kB/s eta 0:09:59
    --------------------------------------- 6.8/376.0 MB 624.2 kB/s eta 0:09:52
    --------------------------------------- 6.8/376.0 MB 624.2 kB/s eta 0:09:52
    --------------------------------------- 7.1/376.0 MB 623.1 kB/s eta 0:09:52
    --------------------------------------- 7.3/376.0 MB 636.2 kB/s eta 0:09:40
    --------------------------------------- 7.6/376.0 MB 648.8 kB/s eta 0:09:28
    --------------------------------------- 7.9/376.0 MB 658.4 kB/s eta 0:09:20
    --------------------------------------- 8.1/376.0 MB 670.2 kB/s eta 0:09:09
    --------------------------------------- 8.4/376.0 MB 683.4 kB/s eta 0:08:58
    --------------------------------------- 8.7/376.0 MB 697.2 kB/s eta 0:08:47
    --------------------------------------- 8.9/376.0 MB 706.2 kB/s eta 0:08:40
    --------------------------------------- 9.2/376.0 MB 711.2 kB/s eta 0:08:36
   - -------------------------------------- 9.4/376.0 MB 715.2 kB/s eta 0:08:33
   - -------------------------------------- 9.4/376.0 MB 715.2 kB/s eta 0:08:33
   - -------------------------------------- 9.7/376.0 MB 714.8 kB/s eta 0:08:33
   - -------------------------------------- 9.7/376.0 MB 714.8 kB/s eta 0:08:33
   - -------------------------------------- 9.7/376.0 MB 714.8 kB/s eta 0:08:33
   - ------------------------------------- 10.0/376.0 MB 699.8 kB/s eta 0:08:44
   - ------------------------------------- 10.0/376.0 MB 699.8 kB/s eta 0:08:44
   - ------------------------------------- 10.0/376.0 MB 699.8 kB/s eta 0:08:44
   - ------------------------------------- 10.2/376.0 MB 690.7 kB/s eta 0:08:50
   - ------------------------------------- 10.2/376.0 MB 690.7 kB/s eta 0:08:50
   - ------------------------------------- 10.5/376.0 MB 690.9 kB/s eta 0:08:49
   - ------------------------------------- 10.7/376.0 MB 693.3 kB/s eta 0:08:47
   - ------------------------------------- 10.7/376.0 MB 693.3 kB/s eta 0:08:47
   - ------------------------------------- 10.7/376.0 MB 693.3 kB/s eta 0:08:47
   - ------------------------------------- 11.0/376.0 MB 681.7 kB/s eta 0:08:56
   - ------------------------------------- 11.0/376.0 MB 681.7 kB/s eta 0:08:56
   - ------------------------------------- 11.0/376.0 MB 681.7 kB/s eta 0:08:56
   - ------------------------------------- 11.3/376.0 MB 669.2 kB/s eta 0:09:05
   - ------------------------------------- 11.3/376.0 MB 669.2 kB/s eta 0:09:05
   - ------------------------------------- 11.3/376.0 MB 669.2 kB/s eta 0:09:05
   - ------------------------------------- 11.5/376.0 MB 661.2 kB/s eta 0:09:12
   - ------------------------------------- 11.5/376.0 MB 661.2 kB/s eta 0:09:12
   - ------------------------------------- 11.8/376.0 MB 659.1 kB/s eta 0:09:13
   - ------------------------------------- 11.8/376.0 MB 659.1 kB/s eta 0:09:13
   - ------------------------------------- 12.1/376.0 MB 659.9 kB/s eta 0:09:12
   - ------------------------------------- 12.1/376.0 MB 659.9 kB/s eta 0:09:12
   - ------------------------------------- 12.3/376.0 MB 659.6 kB/s eta 0:09:12
   - ------------------------------------- 12.3/376.0 MB 659.6 kB/s eta 0:09:12
   - ------------------------------------- 12.6/376.0 MB 659.9 kB/s eta 0:09:11
   - ------------------------------------- 12.6/376.0 MB 659.9 kB/s eta 0:09:11
   - ------------------------------------- 12.8/376.0 MB 661.7 kB/s eta 0:09:09
   - ------------------------------------- 13.1/376.0 MB 661.4 kB/s eta 0:09:09
   - ------------------------------------- 13.1/376.0 MB 661.4 kB/s eta 0:09:09
   - ------------------------------------- 13.4/376.0 MB 664.7 kB/s eta 0:09:06
   - ------------------------------------- 13.6/376.0 MB 671.1 kB/s eta 0:09:00
   - ------------------------------------- 13.9/376.0 MB 675.8 kB/s eta 0:08:56
   - ------------------------------------- 14.2/376.0 MB 683.5 kB/s eta 0:08:50
   - ------------------------------------- 14.4/376.0 MB 690.5 kB/s eta 0:08:44
   - ------------------------------------- 14.7/376.0 MB 693.3 kB/s eta 0:08:42
   - ------------------------------------- 14.7/376.0 MB 693.3 kB/s eta 0:08:42
   - ------------------------------------- 14.9/376.0 MB 688.3 kB/s eta 0:08:45
   - ------------------------------------- 15.2/376.0 MB 696.0 kB/s eta 0:08:39
   - ------------------------------------- 15.7/376.0 MB 711.6 kB/s eta 0:08:27
   - ------------------------------------- 16.0/376.0 MB 720.0 kB/s eta 0:08:20
   - ------------------------------------- 16.3/376.0 MB 726.3 kB/s eta 0:08:16
   - ------------------------------------- 16.5/376.0 MB 731.5 kB/s eta 0:08:12
   - ------------------------------------- 17.0/376.0 MB 742.6 kB/s eta 0:08:04
   - ------------------------------------- 17.3/376.0 MB 747.9 kB/s eta 0:08:00
   - ------------------------------------- 17.3/376.0 MB 747.9 kB/s eta 0:08:00
   - ------------------------------------- 17.6/376.0 MB 748.7 kB/s eta 0:07:59
   - ------------------------------------- 17.8/376.0 MB 748.9 kB/s eta 0:07:59
   - ------------------------------------- 18.1/376.0 MB 753.5 kB/s eta 0:07:55
   - ------------------------------------- 18.4/376.0 MB 758.6 kB/s eta 0:07:52
   - ------------------------------------- 18.6/376.0 MB 760.6 kB/s eta 0:07:50
   - ------------------------------------- 18.9/376.0 MB 765.5 kB/s eta 0:07:47
   - ------------------------------------- 19.1/376.0 MB 770.4 kB/s eta 0:07:44
   -- ------------------------------------ 19.4/376.0 MB 774.2 kB/s eta 0:07:41
   -- ------------------------------------ 19.7/376.0 MB 777.9 kB/s eta 0:07:39
   -- ------------------------------------ 19.7/376.0 MB 777.9 kB/s eta 0:07:39
   -- ------------------------------------ 19.9/376.0 MB 776.7 kB/s eta 0:07:39
   -- ------------------------------------ 19.9/376.0 MB 776.7 kB/s eta 0:07:39
   -- ------------------------------------ 19.9/376.0 MB 776.7 kB/s eta 0:07:39
   -- ------------------------------------ 20.2/376.0 MB 768.1 kB/s eta 0:07:44
   -- ------------------------------------ 20.2/376.0 MB 768.1 kB/s eta 0:07:44
   -- ------------------------------------ 20.4/376.0 MB 766.2 kB/s eta 0:07:44
   -- ------------------------------------ 20.4/376.0 MB 766.2 kB/s eta 0:07:44
   -- ------------------------------------ 20.7/376.0 MB 763.9 kB/s eta 0:07:46
   -- ------------------------------------ 20.7/376.0 MB 763.9 kB/s eta 0:07:46
   -- ------------------------------------ 21.0/376.0 MB 760.0 kB/s eta 0:07:48
   -- ------------------------------------ 21.0/376.0 MB 760.0 kB/s eta 0:07:48
   -- ------------------------------------ 21.2/376.0 MB 759.6 kB/s eta 0:07:48
   -- ------------------------------------ 21.2/376.0 MB 759.6 kB/s eta 0:07:48
   -- ------------------------------------ 21.5/376.0 MB 755.4 kB/s eta 0:07:50
   -- ------------------------------------ 21.8/376.0 MB 758.0 kB/s eta 0:07:48
   -- ------------------------------------ 21.8/376.0 MB 758.0 kB/s eta 0:07:48
   -- ------------------------------------ 22.0/376.0 MB 756.4 kB/s eta 0:07:48
   -- ------------------------------------ 22.0/376.0 MB 756.4 kB/s eta 0:07:48
   -- ------------------------------------ 22.0/376.0 MB 756.4 kB/s eta 0:07:48
   -- ------------------------------------ 22.3/376.0 MB 751.6 kB/s eta 0:07:51
   -- ------------------------------------ 22.5/376.0 MB 755.3 kB/s eta 0:07:48
   -- ------------------------------------ 22.5/376.0 MB 755.3 kB/s eta 0:07:48
   -- ------------------------------------ 22.8/376.0 MB 753.8 kB/s eta 0:07:49
   -- ------------------------------------ 22.8/376.0 MB 753.8 kB/s eta 0:07:49
   -- ------------------------------------ 23.1/376.0 MB 766.2 kB/s eta 0:07:41
   -- ------------------------------------ 23.1/376.0 MB 766.2 kB/s eta 0:07:41
   -- ------------------------------------ 23.1/376.0 MB 766.2 kB/s eta 0:07:41
   -- ------------------------------------ 23.3/376.0 MB 760.2 kB/s eta 0:07:44
   -- ------------------------------------ 23.3/376.0 MB 760.2 kB/s eta 0:07:44
   -- ------------------------------------ 23.6/376.0 MB 763.0 kB/s eta 0:07:42
   -- ------------------------------------ 23.6/376.0 MB 763.0 kB/s eta 0:07:42
   -- ------------------------------------ 23.9/376.0 MB 763.4 kB/s eta 0:07:42
   -- ------------------------------------ 23.9/376.0 MB 763.4 kB/s eta 0:07:42
   -- ------------------------------------ 24.1/376.0 MB 766.2 kB/s eta 0:07:40
   -- ------------------------------------ 24.4/376.0 MB 768.6 kB/s eta 0:07:38
   -- ------------------------------------ 24.4/376.0 MB 768.6 kB/s eta 0:07:38
   -- ------------------------------------ 24.6/376.0 MB 780.6 kB/s eta 0:07:31
   -- ------------------------------------ 24.9/376.0 MB 781.6 kB/s eta 0:07:30
   -- ------------------------------------ 25.2/376.0 MB 785.5 kB/s eta 0:07:27
   -- ------------------------------------ 25.2/376.0 MB 785.5 kB/s eta 0:07:27
   -- ------------------------------------ 25.4/376.0 MB 787.3 kB/s eta 0:07:26
   -- ------------------------------------ 25.7/376.0 MB 793.0 kB/s eta 0:07:22
   -- ------------------------------------ 25.7/376.0 MB 793.0 kB/s eta 0:07:22
   -- ------------------------------------ 26.0/376.0 MB 797.2 kB/s eta 0:07:20
   -- ------------------------------------ 26.0/376.0 MB 797.2 kB/s eta 0:07:20
   -- ------------------------------------ 26.2/376.0 MB 805.3 kB/s eta 0:07:15
   -- ------------------------------------ 26.2/376.0 MB 805.3 kB/s eta 0:07:15
   -- ------------------------------------ 26.5/376.0 MB 799.8 kB/s eta 0:07:17
   -- ------------------------------------ 26.5/376.0 MB 799.8 kB/s eta 0:07:17
   -- ------------------------------------ 26.5/376.0 MB 799.8 kB/s eta 0:07:17
   -- ------------------------------------ 26.7/376.0 MB 801.9 kB/s eta 0:07:16
   -- ------------------------------------ 26.7/376.0 MB 801.9 kB/s eta 0:07:16
   -- ------------------------------------ 26.7/376.0 MB 801.9 kB/s eta 0:07:16
   -- ------------------------------------ 27.0/376.0 MB 804.4 kB/s eta 0:07:14
   -- ------------------------------------ 27.0/376.0 MB 804.4 kB/s eta 0:07:14
   -- ------------------------------------ 27.0/376.0 MB 804.4 kB/s eta 0:07:14
   -- ------------------------------------ 27.3/376.0 MB 795.2 kB/s eta 0:07:19
   -- ------------------------------------ 27.3/376.0 MB 795.2 kB/s eta 0:07:19
   -- ------------------------------------ 27.3/376.0 MB 795.2 kB/s eta 0:07:19
   -- ------------------------------------ 27.3/376.0 MB 795.2 kB/s eta 0:07:19
   -- ------------------------------------ 27.3/376.0 MB 795.2 kB/s eta 0:07:19
   -- ------------------------------------ 27.3/376.0 MB 795.2 kB/s eta 0:07:19
   -- ------------------------------------ 27.3/376.0 MB 795.2 kB/s eta 0:07:19
   -- ------------------------------------ 27.5/376.0 MB 767.4 kB/s eta 0:07:35
   -- ------------------------------------ 27.5/376.0 MB 767.4 kB/s eta 0:07:35
   -- ------------------------------------ 27.5/376.0 MB 767.4 kB/s eta 0:07:35
   -- ------------------------------------ 27.5/376.0 MB 767.4 kB/s eta 0:07:35

In [33]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [35]:
(X_train.shape[1],)

(12,)

In [40]:
## Build our ANN Model

model=Sequential([

    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ##HL1 connected with input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1, activation='sigmoid') ## Output layer
])

c:\Users\gprai\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [42]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [68]:
## Compile the model

model.compile(optimizer=opt, loss="binary_crossentropy",metrics=['accuracy'])

In [69]:
## Setup the tensor board
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard


log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [70]:
## Setup Early Stopping

early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [71]:
## Train the Model

history=model.fit(
    X_train, y_train, validation_data=(X_test,y_test), epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8701 - loss: 0.3190 - val_accuracy: 0.8580 - val_loss: 0.3458
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8705 - loss: 0.3131 - val_accuracy: 0.8565 - val_loss: 0.3459
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8755 - loss: 0.3081 - val_accuracy: 0.8550 - val_loss: 0.3539
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8758 - loss: 0.3032 - val_accuracy: 0.8515 - val_loss: 0.3558
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8731 - loss: 0.3034 - val_accuracy: 0.8620 - val_loss: 0.3508
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8735 - loss: 0.3081 - val_accuracy: 0.8525 - val_loss: 0.3615
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8757 - loss: 0.2956 - val_accuracy: 0.8595 - val_loss: 0.3574
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8753 - loss: 0.2977 - val_accuracy: 0.8580 - val_loss: 0.3571
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8746 - loss: 0.3010 - val_accuracy: 0.8540 - val_loss: 0.3654
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8741 - loss: 0.3023 - val_accuracy: 0.8510 - val_loss: 0.3737
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8777 - loss: 0.2915 - val_accuracy: 0.8580 - val_loss: 0.3660

In [60]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [62]:
## Load TensorBoard

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [65]:
%reload_ext tensorboard

In [67]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 27388), started 2:21:10 ago. (Use '!kill 27388' to kill it.)

In [ ]:
## Load the pickle files